// Export all components from a single file
export { default as AuthForm } from './AuthForm';
export { default as Footer } from './Footer';
export { default as Navbar } from './Navbar';
export { default as ProjectCard } from './ProjectCard';
export { default as SortableTaskItem } from './SortableTaskItem.jsx';
export { default as SortableTaskList } from './SortableTaskList.jsx';
export { default as SupabaseSetup } from './SupabaseSetup';
export { default as TaskItem } from './TaskItem';
